{{- if .Values.frost.db.enableIntegratedDb -}}
{{- if .Values.frost.backup.enabled -}}
{{- $tier := "db" -}}
{{- $fullName := include "frost-server.fullName" (merge (dict "tier" $tier) .) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-backup
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
    component: {{ $tier }}-backup
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "frost-server.name" . }}
      component: {{ $tier }}-backup
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        helm.sh/chart: {{ include "frost-server.chart" . }}
        app: {{ include "frost-server.name" . }}
        component: {{ $tier }}-backup
    spec:
      securityContext:
          {{- toYaml .Values.frost.backup.securityContext | nindent 10 }}
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.frost.backup.image.registry }}/{{ .Values.frost.backup.image.repository }}:{{ .Values.frost.backup.image.tag }}"
          imagePullPolicy: {{ .Values.frost.backup.image.pullPolicy | quote }}
          volumeMounts:
            - name: {{ $fullName }}
              mountPath: {{ .Values.frost.backup.persistence.mountPath }}
          env:
            - name: POSTGRES_DBNAME
              value: {{ .Values.frost.db.database }}
            - name: POSTGRES_HOST
              value: {{ $fullName }}
            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "frost-server.db.secret" . }}
                  key: {{ .Values.frost.secretPasswordKey }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "frost-server.db.secret" . }}
                  key: {{ .Values.frost.secretUsernameKey }}
            - name: REMOVE_BEFORE
              value: "{{ .Values.frost.backup.removeBefore }}"
      volumes:
        - name: {{ $fullName }}
          persistentVolumeClaim:
            claimName: {{ default (list $fullName "backup" | join "-") .Values.frost.backup.persistence.existingClaim }}
  {{- end -}}
  {{- end -}}