apiVersion: v1
name: frost-server
version: 2.1.0
appVersion: 2.1.0-SNAPSHOT
description: The FROST-Server (FRaunhofer Opensource SensorThings-Server) is the first complete, open-source implementation of the OGC SensorThings API Part 1 (Sensing).
keywords:
  - sensorthings-api
  - sensorthings
  - ogc
  - sensing
  - iot
  - frost
home: https://github.com/FraunhoferIOSB/FROST-Server
icon: https://raw.githubusercontent.com/FraunhoferIOSB/FROST-Server/master/docs/images/FROST-Server-darkgrey.png
sources:
  - https://github.com/FraunhoferIOSB/FROST-Server
maintainers:
  - name: Aurelien Bourdon
    url: http://abourdon.github.io
  - name: Philipp Hertweck
    email: philipp.hertweck@iosb.fraunhofer.de
