apiVersion: v1
name: frost-server
version: 1.10.1
appVersion: 1.10
description: The FROST-Server (FRaunhofer Opensource SensorThings-Server) is the first complete, open-source implementation of the OGC SensorThings API Part 1 (Sensing).
keywords:
  - sensorthings-api
  - sensorthings
  - ogc
  - sensing
  - iot
  - frost
home: https://github.com/FraunhoferIOSB/FROST-Server
icon: https://raw.githubusercontent.com/FraunhoferIOSB/FROST-Server/master/images/FROST-Server-darkgrey.png
sources:
  - https://github.com/FraunhoferIOSB/FROST-Server
mainteners:
  - name: Aurelien Bourdon
    url: http://abourdon.github.io
  - name: Philipp Hertweck
    email: philipp.hertweck@iosb.fraunhofer.de
